### ISSUE TITLE
nested redefinition of 'enum hmac_hash' after applying restund patch

### ISSUE THREAD

**Issue by JTallis** [andyet/otalk-server#4]
I tried to apply the page which worked successfully but I'm unable to call "make". This is what show sup in my console.

    root@turn:~/restund-0.4.11# patch -p1 < restund-auth.patch
    patching file modules/auth/auth.c
    root@turn:~/restund-0.4.11# make
      CC [M]  build-x86_64/modules/auth/auth.o
    In file included from modules/auth/auth.c:11:0:
    /usr/local/include/re/re_hmac.h:16:6: error: nested redefinition of 'enum hmac_hash'
     enum hmac_hash {
          ^
    /usr/local/include/re/re_hmac.h:16:6: error: redeclaration of 'enum hmac_hash'
    In file included from /usr/local/include/re/re.h:30:0,
                     from modules/auth/auth.c:10:
    /usr/local/include/re/re_hmac.h:16:6: note: originally defined here
     enum hmac_hash {
          ^
    In file included from modules/auth/auth.c:11:0:
    /usr/local/include/re/re_hmac.h:17:2: error: redeclaration of enumerator 'HMAC_HASH_SHA1'
      HMAC_HASH_SHA1
      ^
    In file included from /usr/local/include/re/re.h:30:0,
                     from modules/auth/auth.c:10:
    /usr/local/include/re/re_hmac.h:17:2: note: previous definition of 'HMAC_HASH_SHA1' was here
      HMAC_HASH_SHA1
      ^
    mk/mod.mk:28: recipe for target 'build-x86_64/modules/auth/auth.o' failed
    make: *** [build-x86_64/modules/auth/auth.o] Error 1

I'm going to guess that the patch has not been updated for restund 0.4.11?

What I had to do was remove the re_hmac.h include after I applied the patch (it would error if I removed it before hand, not too sure why.)

**Comment by fippo** [comment]
no, see https://github.com/otalk/restund for my fork of restund.

**Comment by JTallis** [comment]
Does that fork require the patch or is it already implemented? I did see it before but I wasn't sure whether it was modified or not as the README file wasn't clear about that.

**Comment by fippo** [comment]
it does.
